kind: ConfigMap
metadata:
  creationTimestamp: null
  name: wordpress-envs
apiVersion: v1
data:
  MYSQL_ROOT_PASSWORD: "mysql_root_password"
  MYSQL_DATABASE: "mysql_db"
  MYSQL_USER: "mysql_usr"
  MYSQL_PASSWORD: "mysql_pswd"

  WORDPRESS_DB_NAME: "mysql_db"
  WORDPRESS_DB_HOST: "mysqlservice:3306"
  WORDPRESS_DB_USER: "mysql_usr"
  WORDPRESS_DB_PASSWORD: "mysql_pswd"

  PMA_HOST: "mysqlservice"
  