apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: phpmyadmin-service
  name: phpmyadmin-service
spec:
  ports:
  - name: 8080-80
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: phpmyadmin
  type: ClusterIP
status:
  loadBalancer: {}
