version: '3'

services:
   db:
     image: mysql:5.7
     volumes:
       - ./db_data:/var/lib/mysql
     restart: always
     env_file:
       - .env

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     volumes:
       - ./wp-content:/var/www/html/wp-content
     ports:
       - "8000:80"
     restart: always
     env_file:
       - .env

   phpmyadmin:
     depends_on:
       - db
     image: phpmyadmin/phpmyadmin
     ports:
       - "8080:80"
     env_file:
       - .env

volumes:
    db_data:
    wp-content: